### PATHS ###

# directory of genomic fasta sequences with .fna extension
genomes: brassica_oleracea15/genomes

# directory of annotations with .gff3 extension
annotations: brassica_oleracea15/annotations

# table of matching genome and annotation files
data_table:

# custom scratch directory (default is system default)
scratch:

# output data directories
filtered_genomes: brassica_oleracea15/QC/genomes_filtered
filtered_annotations: brassica_oleracea15/QC/annotations_filtered
proteins: brassica_oleracea15/QC/proteins
functions: brassica_oleracea15/QC/functions
statistics: brassica_oleracea15/QC/statistics
metadata: brassica_oleracea15/QC/metadata

### PARAMETERS ###

# minimum sequence length for the genomic fasta
min_len: 10000

# only keep features of longest isoform
longest_isoform: True

# minimum size of the CDS open reading frame
orf_size: 49

# comma separated list of InterProScan analyses
applications: "TIGRFAM,Pfam"
