### PATHS ###

# directory of genomic fasta sequences with .fna extension
genomes: cauliflower4/genomes

# directory of annotations with .gff3 extension
annotations: cauliflower4/annotations

# table of matching genome and annotation files
data_table:

# custom scratch directory (default is system default)
scratch:

# output data directories
filtered_genomes: cauliflower4/QC/genomes_filtered
filtered_annotations: cauliflower4/QC/annotations_filtered
proteins: cauliflower4/QC/proteins
functions: cauliflower4/QC/functions
statistics: cauliflower4/QC/statistics
metadata: cauliflower4/QC/metadata

### PARAMETERS ###

# minimum sequence length for the genomic fasta
min_len: 10000

# only keep features of longest isoform
longest_isoform: True

# minimum size of the CDS open reading frame
orf_size: 49

# comma separated list of InterProScan analyses
applications: "TIGRFAM,Pfam"
