### PATHS ###

# directory of genomic fasta sequences with .fna extension
genomes: genus_diploid8/genomes

# directory of annotations with .gff3 extension
annotations: genus_diploid8/annotations

# table of matching genome and annotation files
data_table:

# custom scratch directory (default is system default)
scratch:

# output data directories
filtered_genomes: genus_diploid8/QC/genomes_filtered
filtered_annotations: genus_diploid8/QC/annotations_filtered
proteins: genus_diploid8/QC/proteins
functions: genus_diploid8/QC/functions
statistics: genus_diploid8/QC/statistics
metadata: genus_diploid8/QC/metadata

### PARAMETERS ###

# minimum sequence length for the genomic fasta
min_len: 10000

# only keep features of longest isoform
longest_isoform: True

# minimum size of the CDS open reading frame
orf_size: 49

# comma separated list of InterProScan analyses
applications: "TIGRFAM,Pfam"
